---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: video-mediasoup-server
  namespace: stunner-dev
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: video-mediasoup-server
          namespace: vidicue-dev
